apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: graylog
  namespace: flux-system
spec:
  interval: 30m
  url: https://helm.centralus.cloudapp.azure.com/helm/repo
  timeout: 1m

---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: graylog
  namespace: logging
spec:
  interval: 5m
  chart:
    spec:
      chart: graylog/graylog
      sourceRef:
        kind: HelmRepository
        name: graylog
        namespace: flux-system
      version: "5.0.3" # Use the latest stable version
  values:
    graylog:
      ingress:
        enabled: true
        ingressClassName: nginx
        hosts:
          - graylog.sleepy-puppy.com
        tls:
          - secretName: graylog-tls
            hosts:
              - graylog.sleepy-puppy.com
      persistence:
        enabled: true
        size: 10Gi
    mongoDB:
      persistence:
        enabled: true
        size: 10Gi
    elasticsearch:
      persistence:
        enabled: true
        size: 10Gi

