apiVersion: apps/v1
kind: Deployment
metadata:
  name: graylog
  namespace: logging
spec:
  replicas: 1
  selector:
    matchLabels:
      app: graylog
  template:
    metadata:
      labels:
        app: graylog
    spec:
      containers:
        - name: graylog
          image: graylog/graylog:6.2.3
          ports:
            - containerPort: 9000   # Web UI
            - containerPort: 10515   # Syslog TCP
              protocol: TCP
            - containerPort: 10514   # Syslog UDP
              protocol: UDP
            - containerPort: 12201  # GELF TCP
              protocol: TCP
            - containerPort: 12202  # GELF UDP
              protocol: UDP
          env:
            - name: GRAYLOG_PASSWORD_SECRET
              value: "Q2E3YCtry1xg0Tx4eqZRom"  # Random string at least 16 chars
            - name: GRAYLOG_ROOT_PASSWORD_SHA2
              value: "8c6976e5b5410415bde908bd4dee15dfb167a9c873fc4bb8a81f6f2ab448a918"  # SHA256 of "admin"
            - name: GRAYLOG_HTTP_BIND_ADDRESS
              value: "0.0.0.0:9000"
            - name: GRAYLOG_HTTP_EXTERNAL_URI
              value: "https://heith.sleepy-puppy.com/"
            - name: GRAYLOG_ELASTICSEARCH_HOSTS
              value: "http://opensearch:9200"
            - name: GRAYLOG_MONGODB_URI
              value: "mongodb://mongodb:27017/graylog"
            - name: GRAYLOG_TIMEZONE
              value: "America/New_York"
            - name: TZ
              value: "America/New_York"
          volumeMounts:
            - name: graylog-storage
              mountPath: /var/lib/graylog
      volumes:
        - name: graylog-storage
          persistentVolumeClaim:
            claimName: graylog-data-pvc

